### ISSUE TITLE
After compiling with typescript, getting headersSent undefined error

### ISSUE THREAD

**Issue by www-chique** [GiovanniCardamone/express-automatic-routes#18]
### Versions
- **Node Version:** v15.3.0
- **Operating System:** Windows 10
- **Terminal:** Windows Powershell

### Expected Behavior
To mount the routes

### Actual Behavior
Throwing an error as follows
```
Cannot read property 'headersSent' of undefined
TypeError: Cannot read property 'headersSent' of undefined
    at headersSent (D:\Development\Website_Backup\grile\server\node_modules\finalhandler\index.js:256:21)
    at D:\Development\Website_Backup\grile\server\node_modules\finalhandler\index.js:92:17
    at D:\Development\Website_Backup\grile\server\node_modules\express\lib\router\index.js:635:15
    at next (D:\Development\Website_Backup\grile\server\node_modules\express\lib\router\index.js:210:14)
    at Function.handle (D:\Development\Website_Backup\grile\server\node_modules\express\lib\router\index.js:174:3)
    at Function.handle (D:\Development\Website_Backup\grile\server\node_modules\express\lib\application.js:174:10)
    at app (D:\Development\Website_Backup\grile\server\node_modules\express\lib\express.js:39:9)
    at autoload (D:\Development\Website_Backup\grile\server\node_modules\express-automatic-routes\dist\index.js:74:18)
    at scan (D:\Development\Website_Backup\grile\server\node_modules\express-automatic-routes\dist\index.js:38:9)
    at scan (D:\Development\Website_Backup\grile\server\node_modules\express-automatic-routes\dist\index.js:34:13)
    at Object.default_1 [as default] (D:\Development\Website_Backup\grile\server\node_modules\express-automatic-routes\dist\index.js:161:9)
    at Object.<anonymous> (D:\Development\Website_Backup\grile\server\dist\main.js:45:39)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
```

### Steps to Reproduce
I'm a newbie at this, I'll try to explain as much as possible.
I used as following
```
//More imports
import autoroutes from "express-automatic-routes";
const app = express();
autoroutes(app, {
     dir: "./routes",
});
```
The routes load and run properly when running with typescript in development mode, but it gives this error if I compile the typescript and run in javascript mode for production.

I am pretty sure I am doing something wrong.
Many thanks for any assistance.

**Comment by GiovanniCardamone** [comment]
Can you show me the file that handle the request? (the file that is autoloaded by autoroutes)

**Comment by www-chique** [comment]
@GiovanniCardamone - Which file do you mean? The folder structure of the ./routes folder? I'm not sure which file autoroutes load.

**Comment by GiovanniCardamone** [comment]
**the file that is autoloaded by autoroutes**

**Comment by GiovanniCardamone** [comment]
I mean, the autoroutes function will load each file to the corrisponding route by the name.

Can you show me the file who handle the request (yes the file in ./routes directory)

**Comment by www-chique** [comment]
To find out about this error, I am only using just a single file inside the ./routes directory, called
**_profile.ts_**
```
import { Application, Request, Response } from "express";
import { Resource } from "express-automatic-routes";

export default (express: Application) =>
	<Resource>{
		get: {
			middleware: [],
			handler: (req: Request, res: Response) => {
				res.send("Ok");
			},
		},
	};

```

Many thanks for your quick reply and help.
I love Automatic-routes, it's absolutely amazing and saves a lot of time.

**Comment by www-chique** [comment]
Hey, sorry for your time.
I found out the issue. 
Actually one of your questions here gave me the idea to debug and find the specific problem.
Did a few console.logs in that autoload function, and was able to find out exactly which route file was having the problem.

> 
> 
> I mean, the autoroutes function will load each file to the corrisponding route by the name.
> 
> Can you show me the file who handle the request (yes the file in ./routes directory)


For anyone else wondering how stupid I am, it was my mistake:
I forgot to delete the old compiled "dist" folder on every build, so automatic routes was loading a few old broken pages / routes which I am no longer using.

**Comment by GiovanniCardamone** [comment]
thanks for appreciate my work, means a lot!
